# Generated by Django 4.0.2 on 2022-02-11 22:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='current_city',
            field=models.CharField(default='Planrt Earth', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='img',
            field=models.CharField(default='https://eitrawmaterials.eu/wp-content/uploads/2016/09/person-icon.png', max_length=500),
        ),
    ]
