# Generated by Django 4.0.2 on 2022-02-12 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_city_profile_bio_alter_profile_current_city_post_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'cities'},
        ),
    ]
