# Generated by Django 4.0.2 on 2022-02-14 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_post_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['user']},
        ),
        migrations.AddField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2021-07-02 10:36:42.517205-07'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.CharField(default='https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fwww.wysetc.org%2Fwp-content%2Fuploads%2Fsites%2F19%2F2018%2F07%2FAdobeStock_152013093.jpeg&f=1&nofb=1', max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='current_city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.city'),
        ),
    ]
